bbsys/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import render
from django.http.response import HttpResponseRedirect


def index(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/crew/student/query')
    else:
        return HttpResponseRedirect('/crew/login')


urlpatterns = [
    url(r'^$', index),
    url(r'^index/$', index),
    url(r'^admin/', admin.site.urls),
    url(r'^crew/', include("crew.urls", namespace="crew"))
]

crew/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import *

urlpatterns = [
    url(r'^student/$', student_list, name="student_list"),
    url(r'^student/(?P<pk>\d+)$', student_detail, name="student_detail"),
    url(r'^student/query$', student_query, name="student_query"),
    url(r'^student/create$', student_create, name="student_create"),
    url(r'^student/import/$', student_import, name="student_import"),
    url(r'^record/query$', record_query, name="record_query"),
    url(r'^record/input$', record_input, name="record_input"),
    url(r'^record/analysis$', record_analysis, name="record_analysis"),
    url(r'^record/api_analysis$', api_record_analysis),
    url(r'^record/segment/$', record_segment_analysis, name="record_segment_analysis"),
    url(r'^record/average/$', record_average_analysis, name="record_average_analysis"),
    url(r'^record/average_cmp/$', record_average_cmp_analysis, name="record_average_cmp_analysis"),
    url(r'^record/level/$', record_level_analysis, name="record_level_analysis"),
    url(r'^record/level_dist/$', record_level_dist_analysis, name="record_level_dist_analysis"),
    url(r'^login/$', user_login, name="login"),
    url(r'^logout/$', user_logout, name='logout')
]

crew/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.core.paginator import Paginator
from django.db import transaction, IntegrityError

from crispy_forms.utils import render_crispy_form
from django.core.context_processors import csrf
from django.http.response import HttpResponse
from crew import util
import json
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import mixins, generics
from .serializers import DepartmentSerializer, StudentSerializer, PersonSerializer
from .models import Department, Student, Person
from .forms import *
import csv
import xlrd


# Create your views here.

class JSONResponse(HttpResponse):
    def __init__(self, data, **kwargs):
        content = json.dumps(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)


def query(request):
    ctx = {"form": QueryForm()}
    return render(request, "crew/query.html", ctx)


@login_required
@require_http_methods(['GET'])
@csrf_exempt
def student_list(request):
    page_index = int(request.GET.get('page', 1))
    action = request.GET.get('action', 'list')
    query_form = QueryForm(request.GET)
    if query_form.is_valid():
        if action == 'list':
            students = Paginator(query_form.get_query_set(), 1).page(page_index)
            form_html = render_crispy_form(query_form)
            content_html = render_to_string("crew/components/student_list.html", {"students": students})
            return JSONResponse(data={"ok": True, "form_html": form_html, "content_html": content_html})
        else:
            students = query_form.get_query_set()
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="student_info.csv"'
            writer = csv.writer(response)
            writer.writerow(['First row', 'Foo', 'Bar', 'Baz'])
            writer.writerow(['Second row', 'A', 'B', 'C', '"Testing"', "Here's a quote"])
            return response

    form_html = render_crispy_form(query_form)
    return JSONResponse(data={"ok": False, "form_html": form_html})


@login_required
@require_http_methods(['GET', 'POST', 'DELETE'])
@csrf_exempt
def student_detail(request, pk):
    try:
        student = Student.objects.get(pk=pk)
    except Student.DoesNotExist:
        return JSONResponse(data={'ok': False, 'message': '找不到学生'})

    ok = True
    if request.method == 'DELETE':
        student.delete()
        return JSONResponse(data={'ok': True})
    elif request.method == 'POST':
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
        else:
            ok = False
    else:
        form = StudentForm(instance=student)
    ctx = {'action': reverse('crew:student_detail', args=(pk,)), 'form': form}
    content_html = render_to_string("crew/components/student_detail.html", ctx, request=request)
    return JSONResponse(data={'ok': ok, 'content_html': content_html})


@login_required
def student_create(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return JSONResponse(data={'ok': True})
    else:
        form = StudentForm()
    ctx = {'action': request.path, 'form': form}
    content_html = render_to_string("crew/components/student_detail.html", ctx, request=request)
    return JSONResponse(data={'ok': False, 'content_html': content_html})


@login_required
@csrf_exempt
def import_data(request):
    if request.method == 'GET':
        return render(request, 'crew/import.html')
    else:
        if not request.FILES:
            print("NO files")
        file = request.FILES['file']

        try:
            students = util.import_model(file, Student)
        except Exception as e:
            return JSONResponse(data={'ok': False, 'msg': str(e)})

        try:
            with transaction.atomic():
                for s in students:
                    s.save()
        except IntegrityError as e:
            return JSONResponse(data={'ok': False, 'msg': str(e)})
        return JSONResponse(data={'ok': True})

crew/views/record.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.core.paginator import Paginator
from django.db import transaction
from django.db import IntegrityError
from django.forms import formset_factory
from crew.forms import *
from crew.models import *
from crew.util import JSONResponse, debug_print
from crispy_forms.utils import render_crispy_form
from crew import analysis
import json
import functools
import operator

'''
@require_GET
@csrf_exempt
def record_list(request):
    form = QueryRecordForm(request.GET)
    if not form.is_valid():
        return JSONResponse({
            'ok': False,
            'form_html': render_crispy_form(form)
        })

    editable = ('edit' in request.GET)
    students = Student.objects.filter(grade_idx=form.cleaned_data['grade'], class_idx=form.cleaned_data['class_'])
    exam = form.cleaned_data['exam']
    subjects = exam.subjects.all()
    records = Record.objects.filter(student__in=students, exam=exam)

    student_to_row = {s.pk: i for i, s in enumerate(students)}
    subject_to_col = {s.pk: j for j, s in enumerate(subjects)}
    record_table = [[""] * len(subjects) for _ in range(len(students))]
    for rec in records:
        row = student_to_row[rec.student_id]
        col = subject_to_col[rec.subject_id]
        record_table[row][col] = rec.score
    context = {
        'subjects': subjects,
        'data': [
            {'student': student,
             'records': [{'score': score, 'subject_id': sub.id} for score, sub in zip(records, subjects)],
             'total': sum(r for r in records if not isinstance(r, str))}
            for student, records in zip(students, record_table)
            ],
        'editable': True if editable == 1 else False
    }
    return JSONResponse({
        'ok': True,
        'content_html': render_to_string("record/components/record_list.html", context),
        'form_html': render_crispy_form(form)
    })
'''


def record_query(request):
    return render(request, "record/input.html", {'form': InputRecordForm()})


@require_http_methods(['GET', 'POST'])
@csrf_exempt
def record_input(request):
    page_no = int(request.GET.get('page', 1))
    if request.method == 'GET':
        form = InputRecordForm(request.GET)
        if not form.is_valid():
            return JSONResponse({
                'ok': False,
                'form_html': render_crispy_form(form)
            })
        semester = form.cleaned_data['semester']
        exam = form.cleaned_data['exam']
        subject = form.cleaned_data['subject']
        students_all = Student.objects.filter(grade_idx=form.cleaned_data['grade'],
                                              class_idx=form.cleaned_data['class_'])
        page = Paginator(students_all, 10).page(page_no)
        students = page.object_list

        records = Record.objects.filter(semester=semester, subject=subject, exam=exam, student__in=students)
        scores = {r.student_id: r.score for r in records}
        context = {
            'records': [
                {'student': student, 'score': scores[student.pk] if student.pk in scores else ''} for student in
                students
                ],
            'subject': subject, 'exam': exam, 'semester': semester, 'page': page,
        }
        content_html = render_to_string("record/components/record_input.html", context)
        form_html = render_crispy_form(form)
        return JSONResponse({
            'ok': True,
            'content_html': content_html,
            'form_html': form_html,
        })
    else:
        form = InputRecordForm(request.POST)
        if not form.is_valid():
            return JSONResponse({'ok': False, 'msg': "表单错误"})
        data = json.loads(request.POST['data'])
        print(data)
        updated_student = {d['student_id']: d['score'] for d in data}

        semester = form.cleaned_data['semester']
        exam = form.cleaned_data['exam']
        subject = form.cleaned_data['subject']
        records = Record.objects.filter(semester=semester, student__grade_idx=form.cleaned_data['grade'],
                                        subject=subject, exam=exam,
                                        student__class_idx=form.cleaned_data['class_'],
                                        student_id__in=updated_student.keys())
        try:
            with transaction.atomic():
                for record in records:
                    new_score = updated_student[record.student_id]
                    if new_score == '':
                        record.delete()
                    else:
                        record.score = float(new_score)
                        record.save()
                    del updated_student[record.student_id]
                for student_id in updated_student:
                    if updated_student[student_id] != '':
                        Record.objects.create(
                            semester=semester, subject=subject, exam=exam,
                            student_id=student_id, score=float(updated_student[student_id])
                        )
        except IntegrityError:
            return JSONResponse({'ok': False, 'msg': "数据不一致"})
        except ValueError:
            return JSONResponse({'ok': False, 'msg': "分数格式错误"})
        return JSONResponse({'ok': True})


@require_http_methods(['GET', 'POST'])
@csrf_exempt
def record_import(request):
    pass


@require_http_methods(['GET', 'POST'])
@csrf_exempt
def record_analysis(request):
    form = AnalyzeRecordForm()
    return render(request, 'record/analysis.html', {'form': form})


@require_GET
def api_record_analysis(request):
    form = AnalyzeRecordForm(request.GET)
    if form.is_valid():
        sort_by = request.GET['sort_by']
        ascending = int(request.GET['ascending']) == 1
        debug_print(sort_by, ascending)
        tp = form.cleaned_data['analysis_type']
        try:
            if tp == AnalyzeRecordForm.ANALYSIS_RANK:
                debug_print("RANK")
                ana = analysis.RankAnalysis(form, sort_by, ascending)
            elif tp == AnalyzeRecordForm.ANALYSIS_REL:
                debug_print("CMP")
                ana = analysis.RankCmpAnalysis(form, sort_by, ascending)
            else:
                raise analysis.AnalysisError("未实现")
            context = ana.get_context()

            content_html = render_to_string(ana.template_name, context)
            return JSONResponse({
                'ok': True,
                'form_html': render_crispy_form(form),
                'content_html': content_html
            })

        except analysis.AnalysisError as e:
            return JSONResponse({'ok': False, 'form_html': render_crispy_form(form), 'msg': str(e)})
    else:
        debug_print("INVALID")
        return JSONResponse({
            'ok': False,
            'msg': '表单错误',
            'form_html': render_crispy_form(form)
        })


@require_http_methods(['GET', 'POST'])
def record_segment_analysis(request):
    if request.method == 'POST':
        form = AnalysisSegForm(request.POST)
        if form.is_valid():
            try:
                ana = analysis.SegmentAnalysis(form)
                df_list = ana.get_df_list()

                context = {
                    'form': form,
                    'data': [
                        (subject_name, df.to_dict('records'), agg.to_dict(), [int(x) for x in segments.split(',')]) for
                        (subject_name, df, agg, segments) in df_list
                        ],
                }
                return render(request, 'record/segment.html', context)
            except analysis.AnalysisError as e:
                return render(request, 'record/segment.html', {'error': str(e), 'form': form})
    else:
        form = AnalysisSegForm()
    return render(request, 'record/segment.html', {'form': form})


@require_http_methods(['GET', 'POST'])
def record_average_analysis(request):
    if request.method == 'POST':
        form = AnalysisAvgForm(request.POST)
        if form.is_valid():
            try:
                ana = analysis.AverageAnalysis(form)
                df = ana.get_df()
                # print(df)
                context = {
                    'form': form,
                    'data': df.to_dict('records'),
                    'subjects': [s.name for s in ana.show_subjects]
                }
                print(context['data'])
                return render(request, 'record/average.html', context)
            except analysis.AnalysisError as e:
                print(e)
                return render(request, 'record/average.html', {'form': form, 'error': e})
    else:
        form = AnalysisAvgForm()
    return render(request, 'record/average.html', {'form': form})


@require_http_methods(['GET', 'POST'])
def record_average_cmp_analysis(request):
    if request.method == 'POST':
        form = AnalysisAvgCmpForm(request.POST)
        if form.is_valid():
            try:
                ana = analysis.AverageCmpAnalysis(form)
                df, df_cmp = ana.get_df()
                agg, agg_cmp = ana.get_agg()
                context = {
                    'form': form,
                    'data': zip(df.to_dict('records'), df_cmp.to_dict('records')),
                    'subjects': [s.name for s in ana.show_subjects] + ['总分'],
                    'exam': ana.exam.name,
                    'exam_cmp': ana.exam_cmp.name,
                    'agg': agg,
                    'agg_cmp': agg_cmp,
                }
                return render(request, 'record/average_cmp.html', context)
            except analysis.AnalysisError as e:
                return render(request, 'record/average_cmp.html', {'form': form, 'error': e})

    else:
        form = AnalysisAvgCmpForm()

crew/templates/record/analysis.html
{% extends "record/base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="row">
    <div class="col-md-3 col-sm-4">
      {% include "record/components/analysis_panel.html" %}
    </div>
    <div class="col-md-8 col-sm-7">
      <h1>名次分析</h1>
      <div id="id-message"></div>
      <div id="id-main-content">
      </div>
    </div>
  </div>
  <script src="{% static "js/record/analysis.js" %}" type="text/javascript"></script>
{% endblock %}

crew/templates/record/average.html
{% extends "record/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-3 col-sm-4">
      <div class="panel panel-primary panel-compact">
        <div class="panel-heading"><h3 class="panel-title">选择查询条件</h3></div>
        <div class="panel-body">
          <form class="form-horizontal" action="{% url 'crew:record_average_analysis' %}" method="post">
            {% crispy form %}
            <div class="btn-toolbar pull-right">
              <input type="submit" class="btn btn-primary" id="id-btn-stat" value="统计"> </input>
              <button class="btn btn-default" id="id-btn-export"><span class="glyphicon glyphicon-download-alt"></span>导出
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-8 col-sm-7">
      <h1>平均分分析</h1>
      {% if error %}
        <div id="id-message" class="alert alert-danger" role="alert">{{ error }}</div>
      {% endif %}
      <div id="id-main-content">
        {% if data %}
          {% include 'record/components/average_list.html'%}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

crew/templates/record/average_cmp.html
{% extends "record/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-3 col-sm-4">
      <div class="panel panel-primary panel-compact">
        <div class="panel-heading"><h3 class="panel-title">选择查询条件</h3></div>
        <div class="panel-body">
          <form class="form-horizontal" action="{% url 'crew:record_average_cmp_analysis' %}" method="post">
            {% crispy form %}
            <div class="btn-toolbar pull-right">
              <input type="submit" class="btn btn-primary" id="id-btn-stat" value="统计"> </input>
              <button class="btn btn-default" id="id-btn-export"><span class="glyphicon glyphicon-download-alt"></span>导出
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-8 col-sm-7">
      <h1>平均分进退分析</h1>
      {% if error %}
        <div id="id-message" class="alert alert-danger" role="alert">{{ error }}</div>
      {% endif %}
      <div id="id-main-content">
        {% if data %}
          {% include 'record/components/average_cmp_list.html'%}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

crew/templates/record/base.html
{% extends "base.html" %}

{% block body %}
  {% include "nav.html" with cur_module="record" %}
  {% block content %} {% endblock %}
{% endblock %}

crew/templates/record/input.html
{% extends "record/base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="row">
    <div class="col-md-3 col-sm-4">
      {% include "record/components/query_panel.html" %}
    </div>
    <div class="col-md-8 col-sm-7">
      <h1>成绩录入</h1>
      <div id="id-message"></div>
      <div id="id-main-content">
      </div>
    </div>
  </div>
  <script src="{% static "js/record/input.js" %}" type="text/javascript"></script>
{% endblock %}

crew/templates/record/level.html
{% extends "record/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row" xmlns="http://www.w3.org/1999/html">
    <div class="col-md-4 col-sm-4">
      <div class="panel panel-primary panel-compact">
        <div class="panel-heading"><h3 class="panel-title">选择查询条件</h3></div>
        <div class="panel-body">
          <form class="form-horizontal" action="{% url 'crew:record_level_analysis' %}" method="post">
            {% include "record/components/level_panel.html" %}
            <div class="btn-toolbar pull-right">
              <input type="submit" name="stat" class="btn btn-primary" id="id-btn-stat" value="统计"> </input>
              <input type="submit" name="export" class="btn btn-default" id="id-btn-export"><span
              class="glyphicon glyphicon-download-alt"></span>导出</input>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-4">
      <h1>上线分析</h1>
      {% if error %}
        <div id="id-message" class="alert alert-danger" role="alert">{{ error }}</div>
      {% endif %}
      <div id="id-main-content">
        {% if data_list %}
          {% include 'record/components/level_list.html' %}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

crew/templates/record/level_dist.html
{% extends "record/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row" xmlns="http://www.w3.org/1999/html">
    <div class="col-md-4 col-sm-4">
      <div class="panel panel-primary panel-compact">
        <div class="panel-heading"><h3 class="panel-title">选择查询条件</h3></div>
        <div class="panel-body">
          <form class="form-horizontal" action="{% url 'crew:record_level_dist_analysis' %}" method="post">
            {% include "record/components/level_panel.html" %}
            <div class="btn-toolbar pull-right">
              <input type="submit" name="stat" class="btn btn-primary" id="id-btn-stat" value="统计">
              <input type="submit" name="export" class="btn btn-default" id="id-btn-export" value="导出">
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-4">
      <h1>上线分布</h1>
      {% if error %}
        <div id="id-message" class="alert alert-danger" role="alert">{{ error }}</div>
      {% endif %}
      <div id="id-main-content">
        {% if data %}
          {% include 'record/components/level_dist_list.html' %}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

crew/templates/record/query.html
{% extends "record/base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="row">
    <div class="col-md-3 col-sm-4">
      {% include "record/components/query_panel.html" %}
    </div>
    <div class="col-md-8 col-sm-7">
      <h1>成绩管理</h1>
      <div id="id-message"></div>
      <div id="id-main-content">
      </div>
    </div>
  </div>
  <script src="{% static "js/record/query.js" %}" type="text/javascript"></script>
{% endblock %}

crew/templates/record/segment.html
{% extends "record/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-3 col-sm-4">
      <div class="panel panel-primary panel-compact">
        <div class="panel-heading"><h3 class="panel-title">选择查询条件</h3></div>
        <div class="panel-body">
          <form class="form-horizontal" action="{% url 'crew:record_segment_analysis' %}" method="post">
            {% crispy form %}

            <div class="btn-toolbar pull-right">
              <input type="submit" class="btn btn-primary" id="id-btn-stat" value="统计"> </input>
              <button class="btn btn-default" id="id-btn-export"><span class="glyphicon glyphicon-download-alt"></span>导出
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-8 col-sm-7">
      <h1>分数段分析</h1>
      {% if error %}
        <div id="id-message" class="alert alert-danger" role="alert">{{ error }}</div>
      {% endif %}
      <div id="id-main-content">
        {% if data %}
          {% include 'record/components/segment_list.html'%}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}